{
 "title": "Kepler Exporter Dashboard",
 "description": "Dashboard for Kepler Exporter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kepler_container_package_joules_total, container_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}, pod_name)"
    }
   },
   { "name": "coal", "label": "Coal Coeff", "query": "2.23" },
   { "name": "natural_gas", "label": "Natural Gas Coeff", "query": "0.91" },
   { "name": "petroleum", "label": "Petroleum Coeff", "query": "2.13" },
   { "name": "watt_per_second_to_kWh", "query": "0.000000277777777777778" }
  ]
 },
 "panels": [
  { "title": "Carbon Emissions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Carbon Footprint (pounds per kWh per day) in Namespace: $namespace  (PKG+DRAM+OTHER+GPU)",
   "type": "gauge",
   "description": "Using CO2 emissions  by power generation type as reported by US Energy Information Administration https://www.eia.gov/tools/faqs/faq.php?id=74&t=11",
   "gridPos": { "h": 6, "w": 19, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum(increase((kepler_container_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[24h:1m]))) * $watt_per_second_to_kWh ) * $coal",
     "legendFormat": "CO2 Coal"
    },
    {
     "expr": "( sum(increase((kepler_container_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[24h:1m]))) * $watt_per_second_to_kWh ) * $petroleum",
     "legendFormat": "CO2 Petroleum"
    },
    {
     "expr": "( sum(increase((kepler_container_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[24h:1m]))) * $watt_per_second_to_kWh ) * $natural_gas",
     "legendFormat": "CO2 Natural Gas"
    }
   ]
  },
  {
   "title": "Total Power Consumption (W) in Namespace: $namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(irate(kepler_container_package_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[2m]))",
     "legendFormat": "PKG"
    },
    {
     "expr": "sum(irate(kepler_container_dram_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[2m]))",
     "legendFormat": "DRAM"
    },
    {
     "expr": "sum(irate(kepler_container_other_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[2m]))",
     "legendFormat": "OTHER"
    },
    {
     "expr": "sum(irate(kepler_container_gpu_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[2m]))",
     "legendFormat": " GPU"
    }
   ]
  },
  {
   "title": "Total Power Consumption (kWh per day) in Namespace: $namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum (  increase((kepler_container_package_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[24h:1m])  )) * $watt_per_second_to_kWh",
     "legendFormat": "PKG (CORE+UNCORE)"
    },
    {
     "expr": "sum (  increase((kepler_container_dram_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[24h:1m])  )) * $watt_per_second_to_kWh",
     "legendFormat": "DRAM"
    },
    {
     "expr": "sum (  increase((kepler_container_other_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[24h:1m])  )) * $watt_per_second_to_kWh",
     "legendFormat": "OTHER"
    },
    {
     "expr": "sum (  increase((kepler_container_gpu_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[24h:1m])  )) * $watt_per_second_to_kWh",
     "legendFormat": " GPU"
    }
   ]
  }
 ]
}